export const ActivityActions = {
  PROJECT_CREATED: 'PROJECT_CREATED',
  PROJECT_UPDATED: 'PROJECT_UPDATED',

  TASK_CREATED: 'TASK_CREATED',
  TASK_ASSIGNED: 'TASK_ASSIGNED',
  TASK_UPDATED: 'TASK_UPDATED',
  TASK_COMPLETED: 'TASK_COMPLETED',

  CLIENT_CREATED: 'CLIENT_CREATED',
  CLIENT_UPDATED: 'CLIENT_UPDATED',
  CLIENT_DELETED: 'CLIENT_DELETED',

  FREELANCER_CREATED: 'FREELANCER_CREATED',
  FREELANCER_UPDATED: 'FREELANCER_UPDATED',
  FREELANCER_ASSIGNED_TO_PROJECT: 'FREELANCER_ASSIGNED_TO_PROJECT',
  FREELANCER_DELETED: 'FREELANCER_DELETED',
  FREELANCER_MEMBER_REMOVED: 'FREELANCER_MEMBER_REMOVED',
  FREELANCER_MEMBER_UPDATED: 'FREELANCER_MEMBER_UPDATED',
  FREELANCER_UNASSIGNED_FROM_PROJECT: 'FREELANCER_UNASSIGNED_FROM_PROJECT',

  TASK_STATUS_CHANGED: 'TASK_STATUS_CHANGED',
  TASK_SUBMITTED: 'TASK_SUBMITTED',
  TASK_APPROVED_BY_PRESTATAIRE: 'TASK_APPROVED_BY_PRESTATAIRE',
  TASK_VALIDATED_PRESTATAIRE: 'TASK_VALIDATED_PRESTATAIRE',
  TASK_VALIDATED_MANAGER: 'TASK_VALIDATED_MANAGER',

  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_ACTIVATED: 'USER_ACTIVATED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',

  FREELANCER_MEMBER_ADDED: 'FREELANCER_MEMBER_ADDED',

  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
};
